<?php
/**
 * OLM Gutenberg Additions — Cover Module
 *
 * PHP backend logic for Cover block link functionality.
 *
 * This file handles:
 *   - Asset enqueueing (editor + frontend)
 *   - render_block filtering to inject the overlay link HTML
 *   - Translation support for PHP strings
 *
 * Generated by: Lumo 2.0 Max
 */

namespace OLM\GutenbergAdditions;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class OLM_GA_Cover {

	const META_KEY = '_olm_ga_cover_link';

	public static function init() {

		add_action( 'enqueue_block_editor_assets', [ __CLASS__, 'enqueue_editor_assets' ] );
		add_action( 'wp_enqueue_scripts', [ __CLASS__, 'enqueue_frontend_assets' ] );
		add_filter( 'render_block', [ __CLASS__, 'render_cover_link' ], 100, 2 );

	}

	public static function enqueue_editor_assets() {

		wp_enqueue_script(
			'olm-ga-cover',
			OLM_GA_URL . 'modules/cover/olm-cover.js',
			[
				'wp-block-editor',
				'wp-blocks',
				'wp-components',
				'wp-compose',
				'wp-element',
				'wp-hooks',
				'wp-i18n',
			],
			OLM_GA_VERSION,
			true
		);

		wp_set_script_translations(
			'olm-ga-cover',
			'olm-gutenberg-additions',
			OLM_GA_PATH . 'languages'
		);

	}

	public static function enqueue_frontend_assets() {

		wp_enqueue_style(
			'olm-ga-cover',
			OLM_GA_URL . 'modules/cover/olm-cover.css',
			[],
			OLM_GA_VERSION
		);

	}

	public static function render_cover_link( $block_content, $block ) {

		if ( 'core/cover' !== $block['blockName'] ) {
			return $block_content;
		}

		$link_url = isset( $block['attrs']['linkUrl'] ) ? $block['attrs']['linkUrl'] : '';

		if ( empty( $link_url ) ) {
			return $block_content;
		}

		$link_url = esc_url_raw( $link_url );
		$link_url = esc_url( $link_url );

		$target = ( isset( $block['attrs']['linkTarget'] ) && '_blank' === $block['attrs']['linkTarget'] )
			? '_blank'
			: '_self';

		$rel = '_blank' === $target ? ' noopener noreferrer' : '';

		$aria_label = __( 'Cover image link', 'olm-gutenberg-additions' );

		$overlay = sprintf(
			'<a href="%s" class="olm-cover-link-overlay" target="%s"%s aria-label="%s"></a>',
			esc_url( $link_url ),
			'_self' === $target ? '_self' : '_blank',
			$rel ? ' rel="' . $rel . '"' : '',
			esc_attr( $aria_label )
		);

		$block_content = preg_replace(
			'/(<div class=")([^"]*wp-block-cover[^"]*)("[^>]*>)/',
			'$1$2 olm-cover-is-linked$3' . $overlay,
			$block_content,
			1
		);

		return $block_content;

	}

}