/**
 * OLM Gutenberg Additions — Cover Module
 *
 * JavaScript editor enhancements for Cover block link functionality.
 *
 * This file handles:
 *   - Registration of custom block attributes (linkUrl, linkTarget)
 *   - BlockControls toolbar with LinkControl popup
 *   - Save/remove link UI integration
 *   - Translation support for JS strings
 *
 * Generated by: Lumo 2.0 Max
 */

(function (wp) {
	'use strict';

	const { __ } = wp.i18n;

	const { createHigherOrderComponent } = wp.compose;
	const { BlockControls, LinkControl } = wp.blockEditor;
	const { ToolbarGroup, ToolbarButton, Popover } = wp.components;
	const { Fragment, createElement: el, useState } = wp.element;
	const { addFilter } = wp.hooks;

	const OLM_GA_SUPPORTED_BLOCKS = [ 'core/cover' ];

	// Declare custom attributes on Cover block
	function OLM_GA_AddCoverAttributes( settings, name ) {

		if ( ! OLM_GA_SUPPORTED_BLOCKS.includes( name ) ) {
			return settings;
		}

		settings.attributes = {
			...settings.attributes,
			linkUrl: {
				type: 'string',
				default: '',
			},
			linkTarget: {
				type: 'string',
				default: '_self',
			},
		};

		return settings;

	}

	addFilter(
		'blocks.registerBlockType',
		'olm-ga/cover-attributes',
		OLM_GA_AddCoverAttributes
	);

	// Add link control UI
	const OLM_GA_AddCoverLinkControl = createHigherOrderComponent(
		(BlockEdit) => {

			return (props) => {

				if ( ! OLM_GA_SUPPORTED_BLOCKS.includes( props.name ) ) {
					return el( BlockEdit, props );
				}

				const { attributes, setAttributes } = props;
				const { linkUrl = '', linkTarget = '_self' } = attributes;

				const [ isLinkOpen, setIsLinkOpen ] = useState( false );

				const handleLinkChange = ( value ) => {

					setAttributes({
						linkUrl: value?.url || '',
						linkTarget: value?.opensInNewTab ? '_blank' : '_self',
					});

					setIsLinkOpen( false );
				};

				const handleRemoveLink = () => {

					setAttributes({
						linkUrl: '',
						linkTarget: '_self',
					});

					setIsLinkOpen( false );
				};

				return el(
					Fragment,
					{},
					el( BlockEdit, props ),
					el(
						BlockControls,
						{},
						el(
							ToolbarGroup,
							{},
							linkUrl ?
								el( ToolbarButton, {
									icon: 'admin-links',
									label: __( 'Edit Link', 'olm-gutenberg-additions' ),
									isActive: true,
									onClick: () => setIsLinkOpen( ! isLinkOpen ),
								} ) :
								el( ToolbarButton, {
									icon: 'admin-links',
									label: __( 'Add Cover Link', 'olm-gutenberg-additions' ),
									onClick: () => setIsLinkOpen( true ),
								} ),
							linkUrl && el( ToolbarButton, {
								icon: 'editor-unlink',
								label: __( 'Remove Link', 'olm-gutenberg-additions' ),
								onClick: handleRemoveLink,
							} )
						),
					),
					isLinkOpen && el(
						Popover,
						{
							onClose: () => setIsLinkOpen( false ),
						},
						el( LinkControl, {
							value: {
								url: linkUrl || '',
								opensInNewTab: linkTarget === '_blank',
							},
							onChange: handleLinkChange,
							onRemove: handleRemoveLink,
						} )
					)
				);

			};

		},
		'OLM_GA_AddCoverLinkControl'
	);

	addFilter(
		'editor.BlockEdit',
		'olm-ga/cover-link',
		OLM_GA_AddCoverLinkControl
	);

})( window.wp );