<?php
/**
 * OLM Gutenberg Additions — Uninstall
 *
 * This file runs when the plugin is deleted.
 * Currently, no cleanup is required as the plugin
 * stores no persistent data (no options, no tables).
 *
 * Generated by: Lumo 2.0 Max
 */
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
    exit;
}
